import { z } from 'zod';

export const noteSchema = z.object({
  // id is generated by DB or present during update, not usually part of the form itself
  title: z.string().min(1, { message: 'Title cannot be empty' }).max(100, { message: 'Title too long' }),
  content: z.string().min(1, { message: 'Content cannot be empty' }),
  // userId will be added server-side or before sending the request
  // summary will be generated later
});

export type NoteSchema = z.infer<typeof noteSchema>; 